name: pack_arm64
run-name: ${{ github.actor }} build ${{ github.ref_name }} sha ${{ github.sha }}

permissions:
  contents: write
  actions: write
on:
  workflow_call:
    inputs:
      target_version:
        required: true
        type: string
        default: ""
      this_pack_manifest_version:
        required: true
        type: string
        default: ""
jobs:
  build_appstore_package_amd64:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      target_version: ${{ inputs.target_version }}
      target_pack_arch: "arm64"
      this_pack_manifest_version: ${{ inputs.this_pack_manifest_version }}
      this_pack_manifest_arch: "arm"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          pwd
          ls -l
      - name: 下载压缩文件
        run: |
          wget https://github.com/grafana/loki/releases/download/v${{ env.target_version }}/loki-linux-${{ env.target_pack_arch }}.zip
      - name: 解压压缩文件
        run: |
          unzip loki-linux-${{ env.target_pack_arch }}.zip
      - name: 移动可执行文件
        run: |
          mv loki-linux-${{ env.target_pack_arch }} ./app/loki-linux
          chmod a+x ./app/loki-linux
      - name: 替换架构及版本号信息
        run: |
          sed "s/target_version/${{ env.target_version }}/g" -i ./package/manifest
          sed "s/target_pack_arch/${{ env.target_pack_arch }}/g" -i ./package/manifest
          sed "s/this_pack_manifest_version/${{ env.this_pack_manifest_version }}/g" -i ./package/manifest
          sed "s/this_pack_manifest_arch/${{ env.this_pack_manifest_arch }}/g" -i ./package/manifest
          sed "s/this_pack_manifest_platform/${{ env.this_pack_manifest_arch }}/g" -i ./package/manifest
      - name: 打包app.tgz
        run: |
          tar zcvf app.tgz app ui
          mv app.tgz package/
      - name: 打包package
        run: |
          tar zcvf appstore.grafana.loki.${{ env.this_pack_manifest_version }}.${{ env.target_pack_arch }}.tgz package
      - name: 上传应用包
        uses: actions/upload-artifact@master
        with:
          name: appstore.grafana.loki.${{ env.this_pack_manifest_version }}.${{ env.target_pack_arch }}.tgz
          path: appstore.grafana.loki.${{ env.this_pack_manifest_version }}.${{ env.target_pack_arch }}.tgz